import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Clock, CheckCircle, X, AlertTriangle, Info, Calendar, User, BarChart2, Download } from 'lucide-react';
import DashboardLayout from '../components/DashboardLayout';
import { quizService } from '../services/quizService';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface QuestionReview {
    questionId: string;
    text: string;
    options: string[];
    type: string;
    correctAnswers: number[];
    userSelectedOptions: number[];
    isCorrect: boolean;
    marks: number;
    earnedMarks: number;
    explanation?: string;
}

interface AttemptDetails {
    attemptId: string;
    quizTitle: string;
    participant: string;
    score: number;
    totalMarks: number;
    percentage: number;
    isPassed: boolean;
    timeTaken: number;
    submittedAt: string;
    proctoringViolations: number;
    questions: QuestionReview[];
    isCreator?: boolean;
}

const ResultDetailsPage: React.FC = () => {
    const { attemptId } = useParams<{ attemptId: string }>();
    const navigate = useNavigate();
    const [details, setDetails] = useState<AttemptDetails | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const fetchDetails = async () => {
            if (!attemptId) return;
            try {
                const data = await quizService.getAttemptDetails(attemptId);
                setDetails(data);
            } catch (err: any) {
                setError(err.message || 'Failed to load result details');
            } finally {
                setLoading(false);
            }
        };

        fetchDetails();
    }, [attemptId]);

    const handleExportPDF = () => {
        if (!details) return;

        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();

        // Header Title
        doc.setFontSize(22);
        doc.setTextColor(79, 70, 229); // Indigo-600
        doc.text("Quiz Assessment Report", pageWidth / 2, 20, { align: 'center' });

        // Divider
        doc.setDrawColor(226, 232, 240);
        doc.line(20, 25, pageWidth - 20, 25);

        // Basic Info Table
        autoTable(doc, {
            startY: 35,
            head: [['Field', 'Details']],
            body: [
                ['Quiz Title', details.quizTitle],
                ['Participant', details.participant],
                ['Final Score', `${details.score} / ${details.totalMarks} (${details.percentage}%)`],
                ['Result', details.isPassed ? 'PASSED' : 'FAILED'],
                ['Time Taken', `${details.timeTaken} minutes`],
                ['Date', new Date(details.submittedAt).toLocaleString()],
                ['Integrity Status', details.proctoringViolations > 0 ? `Alert (${details.proctoringViolations} violations)` : 'Clean'],
            ],
            theme: 'striped',
            headStyles: { fillColor: [79, 70, 229], textColor: [255, 255, 255], fontStyle: 'bold' },
            styles: { fontSize: 11, cellPadding: 5 },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
        });

        // Question Breakdown Header
        const finalY = (doc as any).lastAutoTable.finalY + 15;
        doc.setFontSize(16);
        doc.setTextColor(30, 41, 59); // Slate-800
        doc.text("Question-by-Question Breakdown", 20, finalY);

        // Questions Table
        autoTable(doc, {
            startY: finalY + 5,
            head: [['No.', 'Question', 'User Response', 'Marks', 'Correct?']],
            body: details.questions.map((q, idx) => {
                const userAns = q.userSelectedOptions.map(i => String.fromCharCode(65 + i)).join(', ');
                return [
                    idx + 1,
                    q.text,
                    userAns || 'Skipped',
                    `${q.earnedMarks}/${q.marks}`,
                    q.isCorrect ? 'SUCCESS' : 'WRONG'
                ];
            }),
            theme: 'grid',
            headStyles: { fillColor: [51, 65, 85], textColor: [255, 255, 255] },
            styles: { fontSize: 9, cellPadding: 4 },
            columnStyles: {
                0: { cellWidth: 10 },
                1: { cellWidth: 80 },
                2: { cellWidth: 40 },
                3: { cellWidth: 20, halign: 'center' },
                4: { cellWidth: 20, halign: 'center' }
            },
        });

        // Footer
        const finalTableY = (doc as any).lastAutoTable.finalY + 20;
        doc.setFontSize(10);
        doc.setTextColor(148, 163, 184); // Slate-400
        doc.text("Generated by Quiz-Platform", pageWidth / 2, finalTableY, { align: 'center' });

        doc.save(`${details.participant.replace(/\s+/g, '_')}_Result.pdf`);
    };

    if (loading) {
        return (
            <DashboardLayout>
                <div className="flex items-center justify-center min-h-[60vh]">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"></div>
                </div>
            </DashboardLayout>
        );
    }

    if (error || !details) {
        return (
            <DashboardLayout>
                <div className="max-w-4xl mx-auto mt-12 p-8 bg-white rounded-3xl border border-slate-200 shadow-sm text-center">
                    <X size={48} className="mx-auto text-red-500 mb-4" />
                    <h2 className="text-2xl font-bold text-slate-800">Error Loading Results</h2>
                    <p className="text-slate-500 mt-2">{error || "Could not find the attempt records."}</p>
                    <button 
                        onClick={() => navigate(-1)} 
                        className="mt-6 px-6 py-2 bg-indigo-600 text-white rounded-xl font-bold transition-all"
                    >
                        Go Back
                    </button>
                </div>
            </DashboardLayout>
        );
    }

    return (
        <DashboardLayout>
            <div className="w-full max-w-5xl mx-auto flex flex-col gap-6 pb-12 px-4 sm:px-6 lg:px-8 mt-4 animate-in fade-in duration-500">
                
                {/* Header */}
                <div className="flex flex-col gap-4">
                    <button
                        onClick={() => navigate(-1)}
                        className="flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-indigo-600 transition-colors w-fit"
                    >
                        <ArrowLeft size={16} /> Back
                    </button>
                    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                        <div>
                            <h1 className="text-2xl md:text-3xl font-black text-slate-800 tracking-tight">
                                {details.quizTitle}
                            </h1>
                            <p className="text-sm text-slate-500 font-medium mt-1 uppercase tracking-wider flex items-center gap-2">
                                <User size={14} className="text-indigo-400" /> {details.participant}'s Result Details
                            </p>
                        </div>
                        <div className="flex items-center gap-3">
                            <button
                                onClick={handleExportPDF}
                                className="px-4 py-2 bg-white border border-slate-200 text-slate-700 hover:bg-slate-50 rounded-xl font-bold flex items-center gap-2 transition-all active:scale-95 text-sm"
                            >
                                <Download size={18} className="text-indigo-600" /> Export PDF
                            </button>
                            <div className={`px-4 py-2 rounded-xl border font-bold flex items-center gap-2 ${details.isPassed ? 'bg-emerald-50 text-emerald-600 border-emerald-100' : 'bg-rose-50 text-rose-600 border-rose-100'}`}>
                                {details.isPassed ? <CheckCircle size={20} /> : <X size={20} />}
                                {details.isPassed ? 'PASSED' : 'FAILED'}
                            </div>
                        </div>
                    </div>
                </div>

                {/* Performance Summary Cards */}
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                    <div className="bg-white p-5 rounded-3xl border border-slate-200 shadow-sm flex flex-col">
                        <span className="text-[0.65rem] font-black text-slate-400 uppercase tracking-widest mb-1">Final Score</span>
                        <div className="flex items-baseline gap-1">
                            <span className="text-3xl font-black text-slate-800">{details.score}</span>
                            <span className="text-sm font-bold text-slate-400">/ {details.totalMarks}</span>
                        </div>
                        <div className="mt-2 w-full bg-slate-100 h-1.5 rounded-full overflow-hidden">
                            <div 
                                className={`h-full rounded-full ${details.isPassed ? 'bg-emerald-500' : 'bg-rose-500'}`} 
                                style={{ width: `${details.percentage}%` }}
                            />
                        </div>
                        <span className="text-xs font-bold text-slate-500 mt-2">{details.percentage}% Overall</span>
                    </div>

                    <div className="bg-white p-5 rounded-3xl border border-slate-200 shadow-sm flex flex-col">
                        <span className="text-[0.65rem] font-black text-slate-400 uppercase tracking-widest mb-1">Time Spent</span>
                        <div className="flex items-center gap-2">
                            <Clock size={24} className="text-indigo-500" />
                            <span className="text-2xl font-black text-slate-800">{details.timeTaken} <span className="text-sm text-slate-400">mins</span></span>
                        </div>
                        <span className="text-xs font-bold text-slate-500 mt-2 flex items-center gap-1">
                            <Calendar size={12} /> {new Date(details.submittedAt).toLocaleDateString()}
                        </span>
                    </div>

                    <div className="bg-white p-5 rounded-3xl border border-slate-200 shadow-sm flex flex-col">
                        <span className="text-[0.65rem] font-black text-slate-400 uppercase tracking-widest mb-1">Integrity Score</span>
                        <div className={`flex items-center gap-2 ${details.proctoringViolations > 0 ? 'text-amber-600' : 'text-emerald-600'}`}>
                            {details.proctoringViolations > 0 ? <AlertTriangle size={24} /> : <BarChart2 size={24} />}
                            <span className="text-2xl font-black">{details.proctoringViolations === 0 ? 'Perfect' : 'Alert'}</span>
                        </div>
                        <span className="text-xs font-bold text-slate-500 mt-2">
                            {details.proctoringViolations} Tab Switch Alerts
                        </span>
                    </div>

                    <div className="bg-white p-5 rounded-3xl border border-slate-200 shadow-sm flex flex-col">
                        <span className="text-[0.65rem] font-black text-slate-400 uppercase tracking-widest mb-1">Questions</span>
                        <div className="flex items-center gap-2 text-indigo-600">
                            <CheckCircle size={24} />
                            <span className="text-2xl font-black text-slate-800">
                                {details.questions.filter(q => q.isCorrect).length}
                                <span className="text-sm text-slate-400"> / {details.questions.length}</span>
                            </span>
                        </div>
                        <span className="text-xs font-bold text-slate-500 mt-2">
                            Correct Answers
                        </span>
                    </div>
                </div>

                {/* Question Review Section */}
                <div className="flex flex-col gap-6 mt-4">
                    <h2 className="text-xl font-black text-slate-800 flex items-center gap-2">
                        Detailed Breakdown
                    </h2>

                    <div className="space-y-6">
                        {details.questions.map((q, idx) => (
                            <div key={q.questionId} className={`bg-white rounded-[32px] border transition-all duration-300 overflow-hidden 
                                ${details.isCreator ? 
                                    (q.isCorrect ? 'border-emerald-100 shadow-emerald-50' : 'border-rose-100 shadow-rose-50') : 
                                    'border-slate-100 shadow-sm'}`}>
                                <div className="p-6 md:p-8 flex flex-col gap-6">
                                    {/* Question Header */}
                                    <div className="flex items-start justify-between gap-4">
                                        <div className="flex gap-3 md:gap-4">
                                            <div className={`shrink-0 w-8 h-8 md:w-10 md:h-10 rounded-xl flex items-center justify-center font-black text-sm md:text-base ${q.isCorrect ? 'bg-emerald-50 text-emerald-600' : 'bg-rose-50 text-rose-600'}`}>
                                                {idx + 1}
                                            </div>
                                            <div className="flex flex-col gap-1">
                                                <h3 className="text-base md:text-lg font-bold text-slate-800 leading-tight">
                                                    {q.text}
                                                </h3>
                                                <div className="flex flex-wrap items-center gap-3 mt-1">
                                                    <span className="px-2 py-0.5 bg-slate-100 text-slate-500 rounded text-[0.65rem] font-bold uppercase tracking-widest">{q.type}</span>
                                                    {details.isCreator && (
                                                        <span className={`flex items-center gap-1 font-bold text-xs ${q.isCorrect ? 'text-emerald-600' : 'text-rose-600'}`}>
                                                            {q.isCorrect ? <CheckCircle size={12} /> : <X size={12} />}
                                                            {q.earnedMarks} / {q.marks} Marks
                                                        </span>
                                                    )}
                                                    {!details.isCreator && (
                                                        <span className="text-slate-500 font-bold text-xs">
                                                            {q.marks} Marks Possible
                                                        </span>
                                                    )}
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Options Grid */}
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                                        {q.options.map((opt, optIdx) => {
                                            const isSelected = q.userSelectedOptions.includes(optIdx);
                                            const isCorrectKey = q.correctAnswers.includes(optIdx);
                                            
                                            let borderClass = isSelected ? 'border-indigo-500 bg-indigo-50/30' : 'border-slate-100 bg-slate-50/50';
                                            let icon = null;

                                            // Only show red/green logic to the creator
                                            if (details.isCreator) {
                                                if (isSelected && isCorrectKey) {
                                                    borderClass = 'border-emerald-500 bg-emerald-50/50';
                                                    icon = <CheckCircle size={16} className="text-emerald-600" />;
                                                } else if (isSelected && !isCorrectKey) {
                                                    borderClass = 'border-rose-500 bg-rose-50/50';
                                                    icon = <X size={16} className="text-rose-600" />;
                                                } else if (!isSelected && isCorrectKey) {
                                                    borderClass = 'border-emerald-500/30 bg-emerald-50/20';
                                                    icon = <CheckCircle size={16} className="text-emerald-500/50" />;
                                                }
                                            } else if (isSelected) {
                                                // Simplified look for attempter
                                                borderClass = 'border-indigo-600 bg-indigo-50/50';
                                                icon = <div className="w-2 h-2 bg-indigo-600 rounded-full"></div>;
                                            }

                                            return (
                                                <div 
                                                    key={optIdx} 
                                                    className={`p-4 rounded-2xl border-2 flex items-center justify-between gap-3 ${borderClass}`}
                                                >
                                                    <div className="flex items-center gap-3">
                                                        <span className={`w-6 h-6 rounded-lg border-2 flex items-center justify-center text-[0.65rem] font-bold ${isSelected ? 'bg-slate-800 border-slate-800 text-white' : 'border-slate-200 text-slate-400'}`}>
                                                            {String.fromCharCode(65 + optIdx)}
                                                        </span>
                                                        <span className={`text-sm font-bold ${isSelected ? 'text-slate-800' : 'text-slate-600'}`}>
                                                            {opt}
                                                        </span>
                                                    </div>
                                                    {icon}
                                                </div>
                                            );
                                        })}
                                    </div>

                                    {/* Explanation */}
                                    {details.isCreator && q.explanation && (
                                        <div className="bg-indigo-50/50 p-4 rounded-2xl border border-indigo-100 flex gap-3">
                                            <Info size={20} className="text-indigo-500 shrink-0" />
                                            <div>
                                                <span className="block text-[0.65rem] font-black text-indigo-400 uppercase tracking-widest mb-1">Explanation</span>
                                                <p className="text-sm text-slate-700 font-medium leading-relaxed">
                                                    {q.explanation}
                                                </p>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </DashboardLayout>
    );
};

export default ResultDetailsPage;
